version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "UTC"
      time: "02:00"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
