name: Debug With Tmate

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  debug:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Max 6 hours (GitHub's hard limit)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure Git User
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Set Up SSH Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Up GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Start Tmate Debugging Session
        uses: mxschmitt/action-tmate@v3
